apiVersion: v1
kind: ConfigMap
metadata:
  name: GrafanaDatasources
  namespace: monitoring
data:
  datasource.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki:3100/
        access: proxy
        isDefault: false
      - name: Prometheus
        type: prometheus
        url: http://prometheus-prometheus:9090/
        access: proxy
        isDefault: true
      - name: AlertManager
        type: alertmanager
        url: http://prometheus-alertmanager:9093/
        access: false
        isDefault: true
        